### ISSUE TITLE
Type of restaurant?

### ISSUE THREAD

**Issue by AngledLuffa** [stanfordnlp/en-worldwide-newswire#11]
```
Straits B-Location
restaurant      O
Pangium B-Facility
in      O
Singapore       B-Location
```

... is Straits a location here?

**Comment by SecroLoL** [comment]
Asked my Singaporean friend to confirm. Surprisingly, Straits should be a NORP here. 

fun fact: **Straits** is a type of cuisine that describes a fusion of Malay and Chinese flavor profiles!

used in a sentence: `Take some time to enjoy the Straits Chinese food in this Singaporean hawker center.`
