### ISSUE TITLE
Facilities in panaf_panafricavisions_5.txt.tsv

### ISSUE THREAD

**Issue by AngledLuffa** [stanfordnlp/en-worldwide-newswire#3]
untitled_output_Dec_03_2022_tsv_iob/batch021-dBdAM5np71Y/REVIEW/panaf_panafricavisions_5.txt.tsv

there are quite a few facilities which do not look like facilities.  for example, `$200 million inland marine port`

**Comment by SecroLoL** [comment]
Fixed
