### ISSUE TITLE
Maria's Rock Cafe inconsistently labeled

### ISSUE THREAD

**Issue by AngledLuffa** [stanfordnlp/en-worldwide-newswire#4]
in 2nd_batch_tsv_iob/batch004-BtJ3NnUPFpw/REVIEW/af_afrol_18.txt.tsv
not sure if in other files as well
sometimes labeled ORG, MISC, or LOC
it generally seems to be the same entity, though

**Comment by SecroLoL** [comment]
Resolved. Changed to facility.
