### ISSUE TITLE
Named museums - ORG, LOC, or Facility?

### ISSUE THREAD

**Issue by AngledLuffa** [stanfordnlp/en-worldwide-newswire#5]
for example, in

untitled_output_Dec_03_2022_tsv_iob/batch022-ykfYnqJyLja/REVIEW/qt_peninsula_15.txt.tsv

3-2-1 Museum

**Comment by SecroLoL** [comment]
I think that Museum is a location that serves a particular purpose. Therefore, a facility -> condensed to LOC in further processing scripts. Thoughts?

**Comment by AngledLuffa** [comment]
That seems reasonable

**Comment by SecroLoL** [comment]
Changed museums to be facilities everywhere in dataset
