### ISSUE TITLE
batch010-kTJlSExiu4x\REVIEW\cn_article_scmp_73.txt.tsv  TikTok, Douyin ORG vs Product

### ISSUE THREAD

**Issue by SecroLoL** [stanfordnlp/en-worldwide-newswire#6]
Douyin	B-Organization
,	O
the	O
Chinese	B-NORP
version	O
of	O
TikTok	B-Organization
,	O
developed	O
an	O
army	O
of	O
influencers	O
to	O
enable	O
it	O
to	O
tap	O
into	O
the	O
e	O
-	O
commerce	O
market	O

Should TikTok and Douyin be Product here?

**Comment by SecroLoL** [comment]
I think that given the context of the sentence, it seems like Douyin having "developed" an army of influencers means that it should be an organization

**Comment by AngledLuffa** [comment]
That's fair, presumably making TikTok an org as well
